# Generated by Django 6.0.5 on 2026-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_direction_fondcontent_historyitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='fond/')),
            ],
            options={
                'verbose_name': 'О фонде',
                'verbose_name_plural': 'О фонде',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Развиваем малые города и сёла Вологодской области', max_length=200)),
                ('hero_text', models.TextField(default='Создаём условия для устойчивого развития территорий через комплексные программы поддержки')),
                ('hero_button_text', models.CharField(default='Узнать о проектах', max_length=100)),
                ('hero_button_link', models.CharField(default='/projects', max_length=200)),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['order'], 'verbose_name': 'Направление работы', 'verbose_name_plural': 'Направления работы'},
        ),
        migrations.AlterModelOptions(
            name='historyitem',
            options={'ordering': ['order'], 'verbose_name': 'Пункт истории', 'verbose_name_plural': 'История фонда'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='direction',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='directions/'),
        ),
        migrations.AlterField(
            model_name='historyitem',
            name='side',
            field=models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
