# Generated by Django 6.0.5 on 2026-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fondpage_homepage_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='help/')),
                ('button_text', models.CharField(default='Поддержать', max_length=100)),
                ('button_type', models.CharField(default='donation', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Карточка помощи',
                'verbose_name_plural': 'Карточки помощи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Как помочь фонду?', max_length=200)),
                ('description', models.TextField(default='Вы можете внести вклад в развитие малых городов и сёл Вологодской области')),
            ],
            options={
                'verbose_name': 'Блок помощи',
                'verbose_name_plural': 'Блок помощи',
            },
        ),
        migrations.DeleteModel(
            name='FondContent',
        ),
        migrations.DeleteModel(
            name='HomeContent',
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
