# Generated by Django 6.0.5 on 2026-05-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_helpcard_helpsection_delete_fondcontent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='helpcard',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='historyitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='projectgallery',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.project'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='vk_url',
            field=models.URLField(blank=True),
        ),
    ]
