# Generated by Django 6.0.5 on 2026-05-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_donationrequest_partnerrequest_volunteerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('button_text', models.CharField(default='Узнать о проектах', max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(default='/projects', max_length=200, verbose_name='Ссылка кнопки')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фоновое изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Слайд героя',
                'verbose_name_plural': 'Слайды героя',
                'ordering': ['order'],
            },
        ),
    ]
