# Generated by Django 6.0.5 on 2026-06-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fondpage',
            name='about_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='helpcard',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='bg_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL логотипа'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения (внешняя ссылка)'),
        ),
        migrations.AddField(
            model_name='projectgallery',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL фото'),
        ),
    ]
